spring:
  application:
    name: "gateway-server"
#  config:
#    import: "optional:configserver:http://localhost:8071/"


  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 9999


  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"



